# _config.yml
title: My Portfolio
critical_css:
  paths: ["/", "/work/"] # Target homepage + work pages
  ignore: [".bi-", ".btn"] # Skip icons/buttons (already fast)

collections:
  illustrations:
    output: true
    permalink: /illustration/:name
